<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJvNxq2k\Eccube_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJvNxq2k/Eccube_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerJvNxq2k.legacy');

    return;
}

if (!\class_exists(Eccube_KernelProdContainer::class, false)) {
    \class_alias(\ContainerJvNxq2k\Eccube_KernelProdContainer::class, Eccube_KernelProdContainer::class, false);
}

return new \ContainerJvNxq2k\Eccube_KernelProdContainer([
    'container.build_hash' => 'JvNxq2k',
    'container.build_id' => '1aa48497',
    'container.build_time' => 1738939649,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJvNxq2k');
